-- Seed: Questions
-- Netflix story-based questions
INSERT INTO questions (title, description, story_description, difficulty, company_tag, pattern_tag, external_url) VALUES
  ('Two Sum',
   'Given an array of integers and a target, return indices of two numbers that add up to target.',
   'You are a Netflix engineer building a recommendation engine. Two users'' preference scores must combine to hit an exact relevance threshold. Find the pair.',
   'easy', 'netflix', 'two-pointers', 'https://leetcode.com/problems/two-sum/'),

  ('Longest Substring Without Repeating Characters',
   'Find the length of the longest substring without repeating characters.',
   'Netflix''s search bar needs to auto-suggest titles. You must find the longest streak of unique characters the user has typed without backspacing.',
   'medium', 'netflix', 'sliding-window', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/'),

  ('LRU Cache',
   'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.',
   'Netflix caches recently watched thumbnails. When memory is full, the least recently viewed thumbnail must be evicted. Design the cache system.',
   'medium', 'netflix', 'linked-list', 'https://leetcode.com/problems/lru-cache/'),

  ('Merge Intervals',
   'Given an array of intervals, merge all overlapping intervals.',
   'Netflix scheduling system has overlapping content release windows. Merge them into non-overlapping time slots for the content delivery team.',
   'medium', 'netflix', 'greedy', 'https://leetcode.com/problems/merge-intervals/'),

  ('Word Search',
   'Given an m x n grid of characters and a word, determine if the word exists in the grid.',
   'Netflix''s content moderation AI scans subtitle grids for flagged words. Implement the search algorithm that checks all directions.',
   'medium', 'netflix', 'backtracking', 'https://leetcode.com/problems/word-search/');

-- Amazon story-based questions
INSERT INTO questions (title, description, story_description, difficulty, company_tag, pattern_tag, external_url) VALUES
  ('Valid Parentheses',
   'Given a string containing brackets, determine if the input string is valid.',
   'Amazon''s code review bot checks if all brackets in submitted code are properly matched. Build the validator.',
   'easy', 'amazon', 'stacks-queues', 'https://leetcode.com/problems/valid-parentheses/'),

  ('Number of Islands',
   'Given a 2D grid of 1s and 0s, count the number of islands.',
   'Amazon logistics maps warehouses on a grid. Connected warehouse zones form a cluster. Count distinct clusters for delivery routing.',
   'medium', 'amazon', 'graphs', 'https://leetcode.com/problems/number-of-islands/'),

  ('Maximum Subarray',
   'Find the contiguous subarray with the largest sum.',
   'Amazon tracks daily profit/loss. Find the best consecutive streak of days that maximizes total profit.',
   'medium', 'amazon', 'dynamic-programming', 'https://leetcode.com/problems/maximum-subarray/'),

  ('Binary Tree Level Order Traversal',
   'Return the level order traversal of a binary tree''s values.',
   'Amazon''s org chart is a tree. HR needs to send announcements level-by-level, starting from the CEO. Build the traversal.',
   'medium', 'amazon', 'trees', 'https://leetcode.com/problems/binary-tree-level-order-traversal/'),

  ('Search in Rotated Sorted Array',
   'Search for a target in a rotated sorted array.',
   'Amazon''s product ID list was rotated after a server migration. Find a specific product ID without re-sorting the entire database.',
   'medium', 'amazon', 'binary-search', 'https://leetcode.com/problems/search-in-rotated-sorted-array/');

-- Pattern-only questions (no company tag)
INSERT INTO questions (title, description, difficulty, pattern_tag, external_url) VALUES
  ('Minimum Window Substring',
   'Find the minimum window in S which contains all characters of T.',
   'hard', 'sliding-window', 'https://leetcode.com/problems/minimum-window-substring/'),

  ('Container With Most Water',
   'Find two lines that together with the x-axis form a container holding the most water.',
   'medium', 'two-pointers', 'https://leetcode.com/problems/container-with-most-water/'),

  ('Find Peak Element',
   'Find a peak element in an array where the element is greater than its neighbors.',
   'medium', 'binary-search', 'https://leetcode.com/problems/find-peak-element/'),

  ('Climbing Stairs',
   'Count distinct ways to climb n stairs taking 1 or 2 steps at a time.',
   'easy', 'dynamic-programming', 'https://leetcode.com/problems/climbing-stairs/'),

  ('Course Schedule',
   'Determine if you can finish all courses given prerequisite pairs.',
   'medium', 'graphs', 'https://leetcode.com/problems/course-schedule/'),

  ('Permutations',
   'Return all possible permutations of a collection of distinct numbers.',
   'medium', 'backtracking', 'https://leetcode.com/problems/permutations/'),

  ('Reverse Linked List',
   'Reverse a singly linked list.',
   'easy', 'linked-list', 'https://leetcode.com/problems/reverse-linked-list/'),

  ('Validate Binary Search Tree',
   'Determine if a binary tree is a valid BST.',
   'medium', 'trees', 'https://leetcode.com/problems/validate-binary-search-tree/'),

  ('Implement Queue Using Stacks',
   'Implement a FIFO queue using only two stacks.',
   'easy', 'stacks-queues', 'https://leetcode.com/problems/implement-queue-using-stacks/'),

  ('Jump Game',
   'Determine if you can reach the last index from the first index.',
   'medium', 'greedy', 'https://leetcode.com/problems/jump-game/');


-- Generated Leetcode problems
INSERT INTO questions (title, description, difficulty, pattern_tag, external_url) VALUES
  ('Two Sum II - Input Array is Sorted', 'The classic opposite-end pointer movement.', 'easy', 'two-pointers', 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/'),
  ('Remove Duplicates from Sorted Array', 'Same-direction fast & slow pointer for in-place modification.', 'easy', 'two-pointers', 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/'),
  ('Squares of a Sorted Array', 'Comparing absolute values from opposite ends.', 'easy', 'two-pointers', 'https://leetcode.com/problems/squares-of-a-sorted-array/'),
  ('Valid Palindrome', 'Moving pointers inward while skipping non-alphanumeric chars.', 'easy', 'two-pointers', 'https://leetcode.com/problems/valid-palindrome/'),
  ('Container With Most Water', 'Optimizing based on height vs width trade-offs.', 'medium', 'two-pointers', 'https://leetcode.com/problems/container-with-most-water/'),
  ('Sort Colors (Dutch National Flag)', 'Using 3 pointers (low, mid, high) to sort in a single pass.', 'medium', 'two-pointers', 'https://leetcode.com/problems/sort-colors-dutch-national-flag/'),
  ('3Sum', 'Fixing one pointer and using Two Pointers on the rest.', 'medium', 'two-pointers', 'https://leetcode.com/problems/3sum/'),
  ('3Sum Closest', 'Tracking the minimum difference while moving pointers.', 'medium', 'two-pointers', 'https://leetcode.com/problems/3sum-closest/'),
  ('Subarray Product Less Than K', 'Same-direction pointers maintaining a valid product window.', 'medium', 'two-pointers', 'https://leetcode.com/problems/subarray-product-less-than-k/'),
  ('Next Permutation', 'Finding the pivot from the right side and swapping.', 'medium', 'two-pointers', 'https://leetcode.com/problems/next-permutation/'),
  ('Trapping Rain Water', 'The ultimate opposite-end pointer question tracking left/right max heights.', 'hard', 'two-pointers', 'https://leetcode.com/problems/trapping-rain-water/'),
  ('4Sum', 'Expanding the 3Sum logic to a fixed double-loop with inner pointers.', 'hard', 'two-pointers', 'https://leetcode.com/problems/4sum/'),
  ('Best Time to Buy and Sell Stock', 'A basic window tracking a minimum price and max profit.', 'easy', 'sliding-window', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/'),
  ('Longest Repeating Character Replacement', 'Using a frequency map to track the "most frequent character" in the window.', 'medium', 'sliding-window', 'https://leetcode.com/problems/longest-repeating-character-replacement/'),
  ('Max Consecutive Ones III', 'Shrinking the window when the "zero count" exceeds K.', 'medium', 'sliding-window', 'https://leetcode.com/problems/max-consecutive-ones-iii/'),
  ('Minimum Size Subarray Sum', 'Shrinking the window from the left as long as the sum condition is met.', 'medium', 'sliding-window', 'https://leetcode.com/problems/minimum-size-subarray-sum/'),
  ('Fruit Into Baskets', 'Variable window tracking exactly 2 unique elements (Hash Map).', 'medium', 'sliding-window', 'https://leetcode.com/problems/fruit-into-baskets/'),
  ('Minimum Window Substring', 'The ultimate variable window tracking required vs. formed characters.', 'hard', 'sliding-window', 'https://leetcode.com/problems/minimum-window-substring/'),
  ('Sliding Window Maximum', 'Hard variation requiring a Monotonic Deque inside the window.', 'hard', 'sliding-window', 'https://leetcode.com/problems/sliding-window-maximum/'),
  ('Substring with Concatenation of All Words', 'Fixed-size window but moving by word_length steps instead of 1.', 'hard', 'sliding-window', 'https://leetcode.com/problems/substring-with-concatenation-of-all-words/'),
  ('Maximum Subarray', 'The absolute core Kadane''s algorithm template.', 'easy', 'arrays', 'https://leetcode.com/problems/maximum-subarray/'),
  ('Maximum Product Subarray', 'Handling negative multipliers by tracking both the current max and min.', 'medium', 'arrays', 'https://leetcode.com/problems/maximum-product-subarray/'),
  ('Subarray Sum Equals K', 'Using a Hash Map with Prefix Sums to find exact contiguous targets.', 'medium', 'arrays', 'https://leetcode.com/problems/subarray-sum-equals-k/'),
  ('Continuous Subarray Sum', 'Storing modulo remainders in a Hash Map to find multiples of K.', 'medium', 'arrays', 'https://leetcode.com/problems/continuous-subarray-sum/'),
  ('Longest Consecutive Sequence', 'Using a HashSet to achieve O(N) time without sorting the array.', 'medium', 'arrays', 'https://leetcode.com/problems/longest-consecutive-sequence/'),
  ('Increasing Triplet Subsequence', 'O(1) space tracking of the first and second minimums.', 'medium', 'arrays', 'https://leetcode.com/problems/increasing-triplet-subsequence/'),
  ('Longest Increasing Subsequence', 'The foundational 1D DP template for non-contiguous elements.', 'medium', 'arrays', 'https://leetcode.com/problems/longest-increasing-subsequence/'),
  ('Number of Matching Subsequences', 'Optimizing multiple subsequence checks using buckets or binary search.', 'medium', 'arrays', 'https://leetcode.com/problems/number-of-matching-subsequences/'),
  ('Maximum Length of Repeated Subarray', 'Applying 2D DP to strictly contiguous subarrays.', 'medium', 'arrays', 'https://leetcode.com/problems/maximum-length-of-repeated-subarray/'),
  ('Shortest Subarray with Sum at Least K', 'Combining Prefix Sums with a Monotonic Deque for optimal time.', 'hard', 'arrays', 'https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/'),
  ('Distinct Subsequences', '2D DP matrix mapping string/array subsequences against targets.', 'hard', 'arrays', 'https://leetcode.com/problems/distinct-subsequences/'),
  ('Range Sum Query - Immutable', 'Creating a prefix array for O(1) repeated lookups.', 'easy', 'arrays', 'https://leetcode.com/problems/range-sum-query-immutable/'),
  ('Maximum Subarray', 'The standard Kadane template: sum = max(num, sum + num).', 'medium', 'arrays', 'https://leetcode.com/problems/maximum-subarray/'),
  ('Maximum Product Subarray', 'Kadane variation tracking both current max AND current min (due to negative numbers).', 'medium', 'arrays', 'https://leetcode.com/problems/maximum-product-subarray/'),
  ('Maximum Sum Circular Subarray', 'Kadane variation: Total Sum minus the Minimum Subarray Sum.', 'medium', 'arrays', 'https://leetcode.com/problems/maximum-sum-circular-subarray/'),
  ('Subarray Sum Equals K', 'The ultimate OA question: Using Prefix Sum + Hash Map to find K.', 'medium', 'arrays', 'https://leetcode.com/problems/subarray-sum-equals-k/'),
  ('Subarray Sums Divisible by K', 'Prefix sum mapped to remainders.', 'medium', 'arrays', 'https://leetcode.com/problems/subarray-sums-divisible-by-k/'),
  ('Contiguous Array', 'Converting 0s to -1s and using Prefix Sum to find equal 0s and 1s.', 'medium', 'arrays', 'https://leetcode.com/problems/contiguous-array/'),
  ('Shortest Subarray with Sum at Least K', 'Combining Prefix Sum with a Monotonic Queue.', 'hard', 'arrays', 'https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/'),
  ('Insert Interval', 'Handling the left, overlapping, and right parts separately.', 'medium', 'arrays', 'https://leetcode.com/problems/insert-interval/'),
  ('Non-overlapping Intervals', 'Greedy variation: Sorting by end time instead of start time.', 'medium', 'arrays', 'https://leetcode.com/problems/non-overlapping-intervals/'),
  ('Find All Duplicates in an Array', 'Cyclic sort finding numbers not at their correct index.', 'medium', 'arrays', 'https://leetcode.com/problems/find-all-duplicates-in-an-array/'),
  ('First Missing Positive', 'The classic hard OA question: Using cyclic sort on unsorted positive/negative arrays.', 'medium', 'arrays', 'https://leetcode.com/problems/first-missing-positive/'),
  ('Minimum Meeting Rooms (Premium)', 'Tracking active intervals using a Min-Heap or Chronological sorting.', 'hard', 'arrays', 'https://leetcode.com/problems/minimum-meeting-rooms-premium/'),
  ('Employee Free Time (Premium)', 'Merging intervals across multiple lists.', 'hard', 'arrays', 'https://leetcode.com/problems/employee-free-time-premium/'),
  ('Find All Numbers Disappeared in an Array', 'Floyd''s cycle detection applied to an array.', 'easy', 'arrays', 'https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/'),
  ('Find the Duplicate Number', 'Cyclic sort when numbers are in range 1 to N.', 'medium', 'arrays', 'https://leetcode.com/problems/find-the-duplicate-number/'),
  ('Valid Perfect Square', 'Binary search on math logic instead of an array.', 'easy', 'binary-search', 'https://leetcode.com/problems/valid-perfect-square/'),
  ('Koko Eating Bananas', 'The absolute classic "minimum rate" allocation template.', 'medium', 'binary-search', 'https://leetcode.com/problems/koko-eating-bananas/'),
  ('Capacity To Ship Packages Within D Days', 'Setting your low (max element) and high (sum of elements).', 'medium', 'binary-search', 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/'),
  ('Minimum Number of Days to Make m Bouquets', 'Tracking contiguous elements within a limit.', 'medium', 'binary-search', 'https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/'),
  ('Find the Smallest Divisor Given a Threshold', 'Division logic with ceiling functions inside the BS check.', 'medium', 'binary-search', 'https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/'),
  ('Minimum Limit of Balls in a Bag', 'Splitting logic inside the validity check function.', 'medium', 'binary-search', 'https://leetcode.com/problems/minimum-limit-of-balls-in-a-bag/'),
  ('Magnetic Force Between Two Balls', 'The "Aggressive Cows" pattern: Maximizing the minimum distance.', 'medium', 'binary-search', 'https://leetcode.com/problems/magnetic-force-between-two-balls/'),
  ('Allocate Books', 'The classic "Minimize the Maximum" student allocation problem.', 'medium', 'binary-search', 'https://leetcode.com/problems/allocate-books/'),
  ('Wood Cutting', 'Calculating remaining heights based on a target cut.', 'medium', 'binary-search', 'https://leetcode.com/problems/wood-cutting/'),
  ('Minimum Time to Complete Trips', 'Handling large numbers (use long long to prevent overflow!).', 'medium', 'binary-search', 'https://leetcode.com/problems/minimum-time-to-complete-trips/'),
  ('Painters Partition Problem', 'Identical structure to Book Allocation, good for cementing the logic.', 'medium', 'binary-search', 'https://leetcode.com/problems/painters-partition-problem/'),
  ('Split Array Largest Sum', 'The exact same underlying code as Book Allocation, just phrased differently.', 'hard', 'binary-search', 'https://leetcode.com/problems/split-array-largest-sum/'),
  ('Minimize Max Distance to Gas Station', 'Binary search on floating-point numbers instead of integers.', 'hard', 'binary-search', 'https://leetcode.com/problems/minimize-max-distance-to-gas-station/'),
  ('Median of Two Sorted Arrays', 'The ultimate BS challenge: dividing two arrays using symmetric cuts.', 'hard', 'binary-search', 'https://leetcode.com/problems/median-of-two-sorted-arrays/'),
  ('First Bad Version', 'Finding the exact boundary of a true/false condition.', 'easy', 'binary-search', 'https://leetcode.com/problems/first-bad-version/'),
  ('Find First and Last Position of Element', 'Running two separate binary searches for the left and right bounds.', 'medium', 'binary-search', 'https://leetcode.com/problems/find-first-and-last-position-of-element/'),
  ('Search in Rotated Sorted Array', 'Finding which half of the array is "normally" sorted.', 'medium', 'binary-search', 'https://leetcode.com/problems/search-in-rotated-sorted-array/'),
  ('Search in Rotated Sorted Array II', 'Handling duplicates (nums[left] == nums[mid]).', 'medium', 'binary-search', 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/'),
  ('Find Minimum in Rotated Sorted Array', 'Looking for the inflection point (the drop).', 'medium', 'binary-search', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/'),
  ('Single Element in a Sorted Array', 'Using odd/even index logic to find the missing pair.', 'medium', 'binary-search', 'https://leetcode.com/problems/single-element-in-a-sorted-array/'),
  ('Find Minimum in Rotated Sorted Array II', 'Handling duplicate elements while finding the minimum.', 'hard', 'binary-search', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/'),
  ('Peak Index in a Mountain Array', 'Same logic as Peak Element, but guaranteed to rise and fall.', 'medium', 'binary-search', 'https://leetcode.com/problems/peak-index-in-a-mountain-array/'),
  ('Search in Rotated Sorted Array', 'Finding which half of the array is "normally" sorted.', 'medium', 'binary-search', 'https://leetcode.com/problems/search-in-rotated-sorted-array/'),
  ('First Unique Character in a String', 'Basic ASCII array counting and single-pass lookup.', 'easy', 'two-pointers', 'https://leetcode.com/problems/first-unique-character-in-a-string/'),
  ('Valid Palindrome II', 'Two pointers with a one-time "skip" allowance.', 'easy', 'two-pointers', 'https://leetcode.com/problems/valid-palindrome-ii/'),
  ('Reverse Vowels of a String', 'Conditional opposite-end pointers (skipping consonants).', 'easy', 'two-pointers', 'https://leetcode.com/problems/reverse-vowels-of-a-string/'),
  ('Permutation in String', 'Fixed-size sliding window comparing two frequency maps.', 'medium', 'two-pointers', 'https://leetcode.com/problems/permutation-in-string/'),
  ('Longest Repeating Character Replacement', 'Replacing characters to maximize window size using counts.', 'medium', 'two-pointers', 'https://leetcode.com/problems/longest-repeating-character-replacement/'),
  ('Sort Characters By Frequency', 'Mapping character counts and sorting them descending.', 'medium', 'two-pointers', 'https://leetcode.com/problems/sort-characters-by-frequency/'),
  ('Group Anagrams', 'Using sorted strings or frequency arrays as Hash Map keys.', 'medium', 'two-pointers', 'https://leetcode.com/problems/group-anagrams/'),
  ('Find All Anagrams in a String', 'Combining anagram frequency checks with a sliding window.', 'medium', 'two-pointers', 'https://leetcode.com/problems/find-all-anagrams-in-a-string/'),
  ('Minimum Number of Steps to Make Two Strings Anagram', 'Calculating the absolute difference between frequency maps.', 'medium', 'two-pointers', 'https://leetcode.com/problems/minimum-number-of-steps-to-make-two-strings-anagram/'),
  ('String Compression', 'In-place read and write pointers directly on a character array.', 'medium', 'two-pointers', 'https://leetcode.com/problems/string-compression/'),
  ('Implement Trie (Prefix Tree)', 'The foundational node-based dictionary tree structure.', 'medium', 'two-pointers', 'https://leetcode.com/problems/implement-trie-prefix-tree/'),
  ('Design Add and Search Words Data Structure', 'Combining a Trie with DFS to handle wildcard ''.'' characters.', 'medium', 'two-pointers', 'https://leetcode.com/problems/design-add-and-search-words-data-structure/'),
  ('Search Suggestions System', 'The exact Trie logic behind autocomplete search bars.', 'medium', 'two-pointers', 'https://leetcode.com/problems/search-suggestions-system/'),
  ('Combination Sum II', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'recursion', 'https://leetcode.com/problems/combination-sum-ii/'),
  ('Combination Sum III', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'recursion', 'https://leetcode.com/problems/combination-sum-iii/'),
  ('Letter Combinations of a Phone Number', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'recursion', 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/'),
  ('Generate Parentheses', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'recursion', 'https://leetcode.com/problems/generate-parentheses/'),
  ('Word Search', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'recursion', 'https://leetcode.com/problems/word-search/'),
  ('Palindrome Partitioning', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'recursion', 'https://leetcode.com/problems/palindrome-partitioning/'),
  ('Restore IP Addresses', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'recursion', 'https://leetcode.com/problems/restore-ip-addresses/'),
  ('N-Queens', 'Master this conceptual problem to improve pattern recognition.', 'hard', 'recursion', 'https://leetcode.com/problems/n-queens/'),
  ('Sudoku Solver', 'Master this conceptual problem to improve pattern recognition.', 'hard', 'recursion', 'https://leetcode.com/problems/sudoku-solver/'),
  ('Word Search II', 'Master this conceptual problem to improve pattern recognition.', 'hard', 'recursion', 'https://leetcode.com/problems/word-search-ii/'),
  ('Linked List Cycle', 'The core cycle template (Floyd''s Tortoise and Hare).', 'easy', 'linked-list', 'https://leetcode.com/problems/linked-list-cycle/'),
  ('Palindrome Linked List', 'Finding the middle, reversing the second half, and comparing.', 'easy', 'linked-list', 'https://leetcode.com/problems/palindrome-linked-list/'),
  ('Intersection of Two Linked Lists', 'Two pointers covering both lists to balance length offsets.', 'easy', 'linked-list', 'https://leetcode.com/problems/intersection-of-two-linked-lists/'),
  ('Happy Number', 'Using cycle detection on math sums instead of nodes.', 'easy', 'linked-list', 'https://leetcode.com/problems/happy-number/'),
  ('Linked List Cycle II', 'Math trick: Finding the exact starting node of the cycle.', 'medium', 'linked-list', 'https://leetcode.com/problems/linked-list-cycle-ii/'),
  ('Remove Nth Node From End of List', 'Fast pointer gets a head start of N steps.', 'medium', 'linked-list', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/'),
  ('Reorder List', 'Combining Fast/Slow (midpoint) + Reversal + Merging.', 'medium', 'linked-list', 'https://leetcode.com/problems/reorder-list/'),
  ('Find the Duplicate Number', 'Cycle detection logic applied to an Array.', 'medium', 'linked-list', 'https://leetcode.com/problems/find-the-duplicate-number/'),
  ('Delete the Middle Node of a Linked List', 'Tracking the node before the slow pointer.', 'medium', 'linked-list', 'https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/'),
  ('Sort List', 'Using Fast/Slow to split the list for Merge Sort.', 'medium', 'linked-list', 'https://leetcode.com/problems/sort-list/'),
  ('Swapping Nodes in a Linked List', 'Locating nodes from the front and back in one pass.', 'medium', 'linked-list', 'https://leetcode.com/problems/swapping-nodes-in-a-linked-list/'),
  ('Odd Even Linked List', 'Segregating nodes based on alternating pointer jumps.', 'medium', 'linked-list', 'https://leetcode.com/problems/odd-even-linked-list/'),
  ('Split Linked List in Parts', 'Calculating total length, then making precise pointer cuts.', 'medium', 'linked-list', 'https://leetcode.com/problems/split-linked-list-in-parts/'),
  ('Circular Array Loop', 'Cycle detection in an array with forward/backward direction rules.', 'hard', 'linked-list', 'https://leetcode.com/problems/circular-array-loop/'),
  ('Remove Linked List Elements', 'Basic pointer skipping to warm up manipulation.', 'easy', 'linked-list', 'https://leetcode.com/problems/remove-linked-list-elements/'),
  ('Merge Two Sorted Lists', 'Stitching pointers without creating new nodes.', 'easy', 'linked-list', 'https://leetcode.com/problems/merge-two-sorted-lists/'),
  ('Reverse Linked List II', 'Reversing only a specific chunk (between left and right).', 'medium', 'linked-list', 'https://leetcode.com/problems/reverse-linked-list-ii/'),
  ('Swap Nodes in Pairs', 'Reversing in chunks of 2.', 'medium', 'linked-list', 'https://leetcode.com/problems/swap-nodes-in-pairs/'),
  ('Rotate List', 'Connecting the tail to the head, then breaking the ring.', 'medium', 'linked-list', 'https://leetcode.com/problems/rotate-list/'),
  ('Add Two Numbers II', 'Reversing both lists, adding, and reversing the result.', 'medium', 'linked-list', 'https://leetcode.com/problems/add-two-numbers-ii/'),
  ('Double a Number Represented As a Linked List', 'Handling carry-over by reversing (or using a stack).', 'medium', 'linked-list', 'https://leetcode.com/problems/double-a-number-represented-as-a-linked-list/'),
  ('Partition List', 'Maintaining two separate chains (less than / greater than) and joining.', 'medium', 'linked-list', 'https://leetcode.com/problems/partition-list/'),
  ('Insertion Sort List', 'Safely breaking and inserting nodes into a sorted portion.', 'medium', 'linked-list', 'https://leetcode.com/problems/insertion-sort-list/'),
  ('Remove Zero Sum Consecutive Nodes', 'Using a dummy node and prefix sums on a linked list.', 'medium', 'linked-list', 'https://leetcode.com/problems/remove-zero-sum-consecutive-nodes/'),
  ('Swapping Nodes in a Linked List', 'Manipulating node values vs actual pointer manipulation.', 'medium', 'linked-list', 'https://leetcode.com/problems/swapping-nodes-in-a-linked-list/'),
  ('Reverse Nodes in k-Group', 'The ultimate OA question. Combining recursion with chunked reversal.', 'hard', 'linked-list', 'https://leetcode.com/problems/reverse-nodes-in-k-group/'),
  ('Reverse Nodes in Even Length Groups', 'A brutal twist on k-Group requiring length counting on the fly.', 'hard', 'linked-list', 'https://leetcode.com/problems/reverse-nodes-in-even-length-groups/'),
  ('Merge k Sorted Lists', 'Pointer manipulation integrated with a Priority Queue (Min-Heap).', 'hard', 'linked-list', 'https://leetcode.com/problems/merge-k-sorted-lists/'),
  ('Next Greater Element II', 'Handling a circular array using the modulo operator %.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/next-greater-element-ii/'),
  ('Daily Temperatures', 'Storing indexes in the stack instead of values to calculate distance.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/daily-temperatures/'),
  ('Online Stock Spanner', 'Designing a class that uses a stack on a continuous data stream.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/online-stock-spanner/'),
  ('Remove K Digits', 'A greedy monotonic stack—popping elements to keep the number small.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/remove-k-digits/'),
  ('Sum of Subarray Minimums', 'Finding both "next smaller" and "previous smaller" simultaneously.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/sum-of-subarray-minimums/'),
  ('Asteroid Collision', 'Stack simulation where elements destroy each other based on conditions.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/asteroid-collision/'),
  ('132 Pattern', 'A highly specific 3-element pointer trick using a stack for the rightmost element.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/132-pattern/'),
  ('Maximum Width Ramp', 'Sorting stack indexes to find the widest valid gap.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/maximum-width-ramp/'),
  ('Shortest Unsorted Continuous Subarray', 'Using the stack to find the exact boundary where sorting breaks down.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/shortest-unsorted-continuous-subarray/'),
  ('Largest Rectangle in Histogram', 'The absolute classic Hard OA question. Mastering area calculation on stack pops.', 'hard', 'stacks-queues', 'https://leetcode.com/problems/largest-rectangle-in-histogram/'),
  ('Maximal Rectangle', 'Applying the Histogram logic row-by-row onto a 2D matrix.', 'hard', 'stacks-queues', 'https://leetcode.com/problems/maximal-rectangle/'),
  ('Trapping Rain Water', 'Solving the classic array pointer problem using a stack instead.', 'hard', 'stacks-queues', 'https://leetcode.com/problems/trapping-rain-water/'),
  ('Sliding Window Maximum', 'The foundational Monotonic Queue (Deque) template.', 'hard', 'stacks-queues', 'https://leetcode.com/problems/sliding-window-maximum/'),
  ('Constrained Subsequence Sum', 'Combining DP with a Monotonic Queue to optimize time.', 'hard', 'stacks-queues', 'https://leetcode.com/problems/constrained-subsequence-sum/'),
  ('Implement Queue using Stacks', 'Moving data between two stacks to reverse the order (LIFO to FIFO).', 'easy', 'stacks-queues', 'https://leetcode.com/problems/implement-queue-using-stacks/'),
  ('Implement Stack using Queues', 'Simulating LIFO behavior using a standard queue.', 'easy', 'stacks-queues', 'https://leetcode.com/problems/implement-stack-using-queues/'),
  ('Min Stack', 'Designing a stack that can return the minimum element in O(1) time.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/min-stack/'),
  ('Evaluate Reverse Polish Notation', 'Parsing a string and performing math operations on popped elements.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/evaluate-reverse-polish-notation/'),
  ('Minimum Add to Make Parentheses Valid', 'Counting unmatched brackets without even needing a physical stack.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/'),
  ('Decode String', 'Handling nested brackets and multipliers (e.g., 3[a2[c]]).', 'medium', 'stacks-queues', 'https://leetcode.com/problems/decode-string/'),
  ('Simplify Path', 'Splitting strings by / and popping directories on ...', 'medium', 'stacks-queues', 'https://leetcode.com/problems/simplify-path/'),
  ('Basic Calculator II', 'Handling operator precedence (* and / before + and -) without parentheses.', 'medium', 'stacks-queues', 'https://leetcode.com/problems/basic-calculator-ii/'),
  ('Longest Valid Parentheses', 'Storing indexes in a stack to measure the length of valid bracket chunks.', 'hard', 'stacks-queues', 'https://leetcode.com/problems/longest-valid-parentheses/'),
  ('Binary Tree Preorder Traversal', 'Root -> Left -> Right.', 'easy', 'trees', 'https://leetcode.com/problems/binary-tree-preorder-traversal/'),
  ('Binary Tree Postorder Traversal', 'Left -> Right -> Root.', 'easy', 'trees', 'https://leetcode.com/problems/binary-tree-postorder-traversal/'),
  ('Maximum Depth of Binary Tree', 'The standard 1 + max(left, right) recursive base case.', 'easy', 'trees', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/'),
  ('Same Tree', 'Traversing two trees simultaneously.', 'easy', 'trees', 'https://leetcode.com/problems/same-tree/'),
  ('Symmetric Tree', 'Mirroring the traversal (Left''s left matches Right''s right).', 'easy', 'trees', 'https://leetcode.com/problems/symmetric-tree/'),
  ('Invert Binary Tree', 'Swapping left and right pointers at every node.', 'easy', 'trees', 'https://leetcode.com/problems/invert-binary-tree/'),
  ('Binary Tree Level Order Traversal', 'The standard BFS template using a Queue.', 'medium', 'trees', 'https://leetcode.com/problems/binary-tree-level-order-traversal/'),
  ('Binary Tree Zigzag Level Order Traversal', 'BFS with a flag to reverse the list insertion every other level.', 'medium', 'trees', 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/'),
  ('Binary Tree Right Side View', 'Modifying BFS to only capture the last element in the queue per level.', 'medium', 'trees', 'https://leetcode.com/problems/binary-tree-right-side-view/'),
  ('Top View of Binary Tree', 'Mapping horizontal distances (HD) to the first visible node.', 'medium', 'trees', 'https://leetcode.com/problems/top-view-of-binary-tree/'),
  ('Bottom View of Binary Tree', 'Mapping horizontal distances but continuously overwriting the node.', 'medium', 'trees', 'https://leetcode.com/problems/bottom-view-of-binary-tree/'),
  ('Boundary Traversal of Binary Tree', 'Combining Left-view, Leaf-nodes, and reversed Right-view.', 'medium', 'trees', 'https://leetcode.com/problems/boundary-traversal-of-binary-tree/'),
  ('Vertical Order Traversal of a Binary Tree', 'Complex BFS/DFS tracking both X and Y coordinates in a TreeMap.', 'hard', 'trees', 'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/'),
  ('Serialize and Deserialize Binary Tree', 'Converting a full tree architecture into a single string and back again.', 'hard', 'trees', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/'),
  ('Balanced Binary Tree', 'Returning -1 to instantly short-circuit the recursion if unbalanced.', 'easy', 'trees', 'https://leetcode.com/problems/balanced-binary-tree/'),
  ('Path Sum', 'Passing a remaining target sum down to the leaf nodes.', 'easy', 'trees', 'https://leetcode.com/problems/path-sum/'),
  ('Lowest Common Ancestor of a BST', 'Using the BST property (values > or < root) to find the split point.', 'medium', 'trees', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-bst/'),
  ('Lowest Common Ancestor of a Binary Tree', 'Returning the exact node where a true signal bubbles up from both left and right.', 'medium', 'trees', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/'),
  ('Path Sum II', 'Tracking the current path in an array and backtracking when popping up.', 'medium', 'trees', 'https://leetcode.com/problems/path-sum-ii/'),
  ('Path Sum III', 'Prefix sum logic applied directly onto a tree path.', 'medium', 'trees', 'https://leetcode.com/problems/path-sum-iii/'),
  ('Sum Root to Leaf Numbers', 'Building an integer dynamically as you traverse down (val * 10 + current).', 'medium', 'trees', 'https://leetcode.com/problems/sum-root-to-leaf-numbers/'),
  ('Count Good Nodes in Binary Tree', 'Passing the "maximum value seen so far" down the recursion tree.', 'medium', 'trees', 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/'),
  ('All Nodes Distance K in Binary Tree', 'Converting a Tree into an undirected Graph (using parent pointers) and running BFS.', 'medium', 'trees', 'https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/'),
  ('Amount of Time for Binary Tree to Be Infected', 'Another variation of mapping parent pointers and running a level-order BFS.', 'medium', 'trees', 'https://leetcode.com/problems/amount-of-time-for-binary-tree-to-be-infected/'),
  ('Step-By-Step Directions From a Binary Tree Node to Another', 'Finding the LCA, then generating "L", "R", and "U" string paths.', 'medium', 'trees', 'https://leetcode.com/problems/step-by-step-directions-from-a-binary-tree-node-to-another/'),
  ('Construct Binary Tree from Preorder and Inorder', 'Rebuilding a tree by mapping array indexes.', 'medium', 'trees', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder/'),
  ('Validate Binary Search Tree', 'Passing strict min and max bounds down to children.', 'medium', 'trees', 'https://leetcode.com/problems/validate-binary-search-tree/'),
  ('Binary Tree Maximum Path Sum', 'Handling negative numbers while calculating the ultimate diameter-like sum.', 'hard', 'trees', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/'),
  ('K Closest Points to Origin', 'Calculating distance formulas and keeping the bottom K elements.', 'medium', 'heap-pq', 'https://leetcode.com/problems/k-closest-points-to-origin/'),
  ('Task Scheduler', 'Using a Max-Heap alongside a Queue to handle "cooldown" periods.', 'medium', 'heap-pq', 'https://leetcode.com/problems/task-scheduler/'),
  ('Reorganize String', 'Popping the top two elements from a Max-Heap to alternate them.', 'medium', 'heap-pq', 'https://leetcode.com/problems/reorganize-string/'),
  ('Kth Smallest Element in a Sorted Matrix', 'Pushing matrix coordinates into a heap for multi-way merging.', 'medium', 'heap-pq', 'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/'),
  ('Find K Pairs with Smallest Sums', 'Tracking combinations from two arrays using a heap.', 'medium', 'heap-pq', 'https://leetcode.com/problems/find-k-pairs-with-smallest-sums/'),
  ('Seat Reservation Manager', 'Simple class design wrapping a Min-Heap.', 'medium', 'heap-pq', 'https://leetcode.com/problems/seat-reservation-manager/'),
  ('Merge k Sorted Lists', 'Pushing Linked List nodes directly into the heap.', 'hard', 'heap-pq', 'https://leetcode.com/problems/merge-k-sorted-lists/'),
  ('Find Median from Data Stream', 'The classic Two-Heap pattern (balancing a Max-Heap and a Min-Heap).', 'hard', 'heap-pq', 'https://leetcode.com/problems/find-median-from-data-stream/'),
  ('Sliding Window Median', 'Two-Heaps combined with lazy deletion as a window moves.', 'hard', 'heap-pq', 'https://leetcode.com/problems/sliding-window-median/'),
  ('IPO', 'Two-Heaps used sequentially (Min-Heap for cost, Max-Heap for profit).', 'hard', 'heap-pq', 'https://leetcode.com/problems/ipo/'),
  ('Min Cost Climbing Stairs', 'Adding a cost array to the basic state transition.', 'easy', 'dynamic-programming', 'https://leetcode.com/problems/min-cost-climbing-stairs/'),
  ('House Robber', 'The classic "include or exclude" 1D DP.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/house-robber/'),
  ('House Robber II', 'Handling a circular array condition.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/house-robber-ii/'),
  ('Decode Ways', 'String parsing using 1D DP.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/decode-ways/'),
  ('Combination Sum IV', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/combination-sum-iv/'),
  ('Longest Common Subsequence', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/longest-common-subsequence/'),
  ('Palindromic Substrings', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/palindromic-substrings/'),
  ('Maximum Product Subarray', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/maximum-product-subarray/'),
  ('Edit Distance', 'Master this conceptual problem to improve pattern recognition.', 'hard', 'dynamic-programming', 'https://leetcode.com/problems/edit-distance/'),
  ('Longest Palindromic Subsequence', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/longest-palindromic-subsequence/'),
  ('Target Sum', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/target-sum/'),
  ('Burst Balloons', 'Master this conceptual problem to improve pattern recognition.', 'hard', 'dynamic-programming', 'https://leetcode.com/problems/burst-balloons/'),
  ('Coin Change II', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/coin-change-ii/'),
  ('Unique Paths', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/unique-paths/'),
  ('Triangle', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'dynamic-programming', 'https://leetcode.com/problems/triangle/'),
  ('Number of Islands', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'graphs', 'https://leetcode.com/problems/number-of-islands/'),
  ('Max Area of Island', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'graphs', 'https://leetcode.com/problems/max-area-of-island/'),
  ('Surrounded Regions', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'graphs', 'https://leetcode.com/problems/surrounded-regions/'),
  ('Clone Graph', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'graphs', 'https://leetcode.com/problems/clone-graph/'),
  ('Longest Increasing Path in a Matrix', 'Master this conceptual problem to improve pattern recognition.', 'hard', 'graphs', 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/'),
  ('Course Schedule II', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'graphs', 'https://leetcode.com/problems/course-schedule-ii/'),
  ('Alien Dictionary', 'Master this conceptual problem to improve pattern recognition.', 'hard', 'graphs', 'https://leetcode.com/problems/alien-dictionary/'),
  ('As Far from Land as Possible', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'graphs', 'https://leetcode.com/problems/as-far-from-land-as-possible/'),
  ('01 Matrix', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'graphs', 'https://leetcode.com/problems/01-matrix/'),
  ('Word Ladder', 'Master this conceptual problem to improve pattern recognition.', 'hard', 'graphs', 'https://leetcode.com/problems/word-ladder/'),
  ('Min Cost to Connect All Points', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'graphs', 'https://leetcode.com/problems/min-cost-to-connect-all-points/'),
  ('Lemonade Change', 'Master this conceptual problem to improve pattern recognition.', 'easy', 'greedy', 'https://leetcode.com/problems/lemonade-change/'),
  ('Jump Game', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'greedy', 'https://leetcode.com/problems/jump-game/'),
  ('Jump Game II', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'greedy', 'https://leetcode.com/problems/jump-game-ii/'),
  ('Gas Station', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'greedy', 'https://leetcode.com/problems/gas-station/'),
  ('Partition Labels', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'greedy', 'https://leetcode.com/problems/partition-labels/'),
  ('Valid Parenthesis String', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'greedy', 'https://leetcode.com/problems/valid-parenthesis-string/'),
  ('Non-overlapping Intervals', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'greedy', 'https://leetcode.com/problems/non-overlapping-intervals/'),
  ('Minimum Number of Arrows to Burst Balloons', 'Master this conceptual problem to improve pattern recognition.', 'medium', 'greedy', 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/'),
  ('Candy', 'Master this conceptual problem to improve pattern recognition.', 'hard', 'greedy', 'https://leetcode.com/problems/candy/'),
  ('Single Number', 'The absolute core XOR trick (N ^ N = 0).', 'easy', 'greedy', 'https://leetcode.com/problems/single-number/'),
  ('Number of 1 Bits', 'Using n & (n - 1) to drop the lowest set bit.', 'easy', 'greedy', 'https://leetcode.com/problems/number-of-1-bits/'),
  ('Counting Bits', 'Applying basic DP to bit counting (offsetting by powers of 2).', 'easy', 'greedy', 'https://leetcode.com/problems/counting-bits/'),
  ('Reverse Bits', 'Shifting bits left and right to rebuild a 32-bit integer.', 'easy', 'greedy', 'https://leetcode.com/problems/reverse-bits/'),
  ('Missing Number', 'Using XOR on ranges to find the missing integer (alternative to cyclic sort).', 'easy', 'greedy', 'https://leetcode.com/problems/missing-number/'),
  ('Sum of Two Integers', 'Adding numbers without the ''+'' operator using XOR and AND (carry).', 'medium', 'greedy', 'https://leetcode.com/problems/sum-of-two-integers/'),
  ('Single Number III', 'Finding TWO unique numbers by isolating the rightmost set bit to create two XOR buckets.', 'medium', 'greedy', 'https://leetcode.com/problems/single-number-iii/');
